version: '1.0'

services:
  postgres_db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data


  coffee:
    image: coffee:1.0.1
    build:
      context: ./back/
      dockerfile: Dockerfile
    depends_on:
      - postgres_db
    expose:
      - 8080
      - 9090
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=qwerty
    ports:
      - "8080:8080"
      - "9090:9090"
    restart: unless-stopped

  machine1:
    image: machine:1.0.1
    build:
      context: ./machine/
      dockerfile: Dockerfile
    depends_on:
      - coffee
    expose:
      - 9000
      - 9090
    environment:
      - SERVER_PORT=9000
      - BACK_HOST=coffee
    ports:
      - "9000:9000"
    restart: unless-stopped

  machine2:
    image: machine:1.0.1
    build:
      context: ./machine/
      dockerfile: Dockerfile
    depends_on:
      - coffee
    expose:
      - 9001
      - 9090
    environment:
      - SERVER_PORT=9001
      - BACK_HOST=coffee
    ports:
      - "9001:9001"
    restart: unless-stopped

  vaadin:
    image: vaadin:1.0.1
    build:
      context: ./vaadin/
      dockerfile: Dockerfile
    depends_on:
      - coffee
    expose:
      - 8081
    environment:
      - COFFEE_URL=coffee:8080
    ports:
      - "8081:8081"
    restart: unless-stopped