coffee-machine:
  water: 650
  milk: 540
  beans: 120
  cups: 9

espresso:
  time-to-make: 2000
  water: 250
  beans: 16

latte:
  time-to-make: 3000
  water: 350
  milk: 75
  beans: 20

cappuccino:
  time-to-make: 4500
  water: 200
  milk: 100
  beans: 12

machine:
  clean: 1000
  restart: 1000
